config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "dashboard/dashboard#home"

  namespace :dashboard do
    get '/' => 'dashboard#home'
    resources :boxes do
      resources :items
      resources :accesses
    end
  end

end

app/models/access.rb
class Access < ActiveRecord::Base
  belongs_to :user
  belongs_to :box

  def owner?
    self.role == 'owner'
  end

end

app/models/box.rb
class Box < ActiveRecord::Base
  has_many :accesses
  has_many :users, through: :accesses

  has_many :items

  validates :label, presence: true

  def method_missing(m, *args, &block)
    method = m.to_s

    # expire_in_<num_days>_days
    if method.match(/expire_in_[0-9]+_days/)
      define_singleton_method(m) do
        day = m[/[0-9]+/].to_i
        self.items.where("expire_date <= '#{day.days.from_now.strftime("%Y-%m-%d")}'").order(expire_date: :asc)
      end
      self.send(m.to_s)
    end

  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :box

  validates :label, :expire_date, :amount, presence: true
  validates :amount, numericality: {only_integer: true, greater_than: 0, less_than: 100}
  validate :expired_date_must_be_today_onward

  def expired_date_must_be_today_onward
    if self.expire_date < Date.today
      errors.add(:expire_date, "cannot be in the past.")
    end
  end

  def expire_in
    days = (self.expire_date - Date.current).to_i

    return "today" if days == 0
    return "expired" if days < 0

    days.to_s + ' day'.pluralize(days)
  end

end

app/models/user.rb
class User < ActiveRecord::Base  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :accesses
  has_many :boxes, through: :accesses  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/dashboard/accesses_controller.rb
class Dashboard::AccessesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_and_authorize_resources

  def index
    @accesses = @box.accesses
  end

  def new
    @access = @box.accesses.new
  end

  def create
    access = @box.accesses.new
    user = User.find_by(email: access_params[:email])
    if user
      access.user = user
      access.role = access_params[:role]
      unless access.save
        flash[:alert] = "Error occurs !"
      end
    else
      flash[:alert] = "Another user with #{access_params[:email]} is not found."
    end
    redirect_to dashboard_box_accesses_path(@box)
  end

  def show

  end

  private
    def access_params
      params.require(:access).permit(:box_id, :role, :email, :role)
    end
    def load_and_authorize_resources
      @box = current_user.boxes.find_by(id: params[:box_id])
      @access = @box.accesses.find_by(user_id: current_user.id)
      unless @access.owner?
        flash[:notice] = "You don't have permission to edit #{@box.label}."
        redirect_to dashboard_boxes_path unless @access.owner?
      end
    end

end

app/controllers/dashboard/boxes_controller.rb
class Dashboard::BoxesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_and_authorize_resources, only: [:edit, :update, :destroy]
  #before_action :delay

  def index
    @boxes = current_user.boxes
  end

  def new
    @box = Box.new
  end

  def create
    # create empty model
    access = Access.new
    @box = current_user.boxes.new(box_params)
    # complete access model
    access.box = @box
    access.user = current_user
    access.role = "owner"
    # write to db
    # if box is successfully saved but access fails, remove that box
    begin
      @box.save!
      access.save!
      redirect_to dashboard_boxes_path
    rescue
      flash.now[:alert] = @box.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @access.owner?
      result = @box.update(box_params)
      unless result
        flash[:alert] = @box.errors.full_messages
      end
    else
      flash[:notice] = "You don't have permission to update #{@box.label} box."
    end
    @redirect_path = params[:dest]
  end

  def destroy
    if @access.owner?
      @box.accesses.destroy_all
      @box.items.destroy_all
      @box.destroy
    else
      flash[:notice] = "You don't have permission to delete #{@box.label} box."
    end
    @redirect_path = params[:dest]
  end

  private
    def box_params
      params.require(:box).permit(:label)
    end
    def load_and_authorize_resources
      @box = current_user.boxes.find_by(id: params[:id])
      @access = @box.accesses.find_by(user_id: current_user.id)
    end
    def delay
      sleep 1
    end

end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController

  before_action :authenticate_user!

  def home
    @boxes = current_user.boxes
  end

end

app/controllers/dashboard/items_controller.rb
class Dashboard::ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_shared_data
  before_action :load_box
  # before_action :delay

  def index
    @items = @box.items
  end

  def new
    @item = @box.items.new
    @today = Date.today.strftime('%Y-%m-%d')
  end

  def create
    @item = @box.items.new(item_params)
    if @item.save
      flash.now[:notice] = "#{@item.label} is successfully added."
      redirect_to new_dashboard_box_item_path(@box)
    else
      flash.now[:alert] = @item.errors.full_messages
      render :new
    end
  end

  def edit
    @item = @box.items.find_by(id: params[:id])
    @mode = params[:mode]
  end

  def update
    item = @box.items.find_by(id: params[:id])
    success = item.update(item_params)
    unless success
      flash[:alert] = item.errors.full_messages
    end
    @redirect_path = params[:dest]
  end

  def destroy
    item = @box.items.find_by(id: params[:id])
    @error = item.nil?
    if item
      item.destroy
    else
      flash[:alert] = "Item doesn't exist."
    end
    @redirect_path = params[:dest]
  end

  private
    def item_params
      params.require(:item).permit(:label, :expire_date, :amount)
    end
    def load_shared_data
      @this_year = Date.today.strftime('%Y')
      @max_day = Date.today.end_of_month.strftime('%d')
    end
    def load_box
      @box = current_user.boxes.find_by(id: params[:box_id])
    end
    def delay
      sleep 1
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_dialog_loading(id)
    html = <<-HTML
      <div id="#{id}" class="modal fade">
        #{render 'dashboard/shared/loading_dialog'}
      </div>
      <script>
        $("##{id}").on("show.bs.modal", function (e) {
          $("##{id}").html('#{escape_javascript(render 'dashboard/shared/loading_dialog')}');
        });
      </script>  
    HTML
    html.html_safe
  end

end

app/helpers/dashboard/accesses_helper.rb
module Dashboard::AccessesHelper
end

app/helpers/dashboard/box_helper.rb
module Dashboard::BoxHelper
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/dashboard/items_helper.rb
module Dashboard::ItemsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="error_explanation">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/dashboard/accesses/index.html.erb
<% breadcrumb :accesses, @box %>

<div class="container">
  <section class="boxes">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <h1>Accesses</h1>
        <p>
          List of user that has access to <b><%= @box.label %></b> box.
        </p>
        <%= render "dashboard/shared/flash" %>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th>#</th>
              <th>User</th>
              <th>Role</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @accesses.each_with_index do |access, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= access.user.email %></td>
                <td><%= access.role.capitalize %></td>
                <td>
                  <%= link_to '<i class="material-icons md-18 md-dark">edit</i>'.html_safe,
                               "edit_dashboard_box_path(box)",
                               data: {toggle: 'modal', target: '#edit-box'}, remote: true %>
                </td>
              <tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </section>
</div>

<!-- fab btn -->
<div class="abs-fab">
  <a href="<%= new_dashboard_box_access_path %>" class="btn btn-info btn-fab">
    <i class="material-icons">add</i>
  </a>
</div>
<!-- .fab btn -->

<!-- dialogs -->
<div id="edit-box" class="modal"></div>
<!-- .dialogs -->

app/views/dashboard/accesses/new.html.erb
<% breadcrumb :new_access, @box %>

<div class="container">
  <section class="boxes">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <h1>Share with</h1>
        <p>
          Share <b><%= @box.label %></b> with other people.
        </p>
        <%= render "dashboard/shared/flash" %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <%= form_for @access, url: {action: "create"} do |f| %>
          <div class="form-group label-static">
            <label class="control-label">Email</label>
            <%= text_field_tag 'access[email]', nil, class: 'form-control'%>
          </div>
          <div class="form-group label-static">
            <label class="control-label">Role</label>
            <hr>
            <div class="radio radio-primary">
              <label>
                <%= radio_button_tag 'access[role]', 'user' %>
                User (Only Add/Remove Items)
              </label>
            </div>
            <div class="radio radio-primary">
              <label>
                <%= radio_button_tag 'access[role]', 'owner' %>
                Owner (Full control)
              </label>
            </div>
          </div>
        <div>
          <%= f.submit "Share", class: "btn btn-raised btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</section>
</div>

app/views/dashboard/accesses/show.html.erb
WoW

app/views/dashboard/boxes/destroy.js.erb
Turbolinks.visit('<%= @redirect_path %>');

app/views/dashboard/boxes/edit.js.erb
$('.modal').html('<%= escape_javascript(render "dashboard/boxes/forms/modal_edit") %>');

$('.btn-modal').on('click', function() {  
  $(this).attr('disabled', 'disabled');
  $(this).parents('form').submit()
});

app/views/dashboard/boxes/forms/_modal_edit.html.erb
<%= form_for @box,
             url: dashboard_box_path(@box, dest: dashboard_boxes_path),
             method: :patch, remote: true do |f| %>

    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title"><%= @box.label %></h4>
        </div>
        <div class="modal-body">
          <div class="form-group label-static">
            <label class="control-label">Box Name</label>
            <%= f.text_field :label, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <%= link_to "Delete",
                  dashboard_box_path(@box, @item, dest: "#{dashboard_boxes_path}"),
                  method: :delete, remote: true, class: "btn btn-raised btn-danger btn-modal" %>
          <%= f.submit "Save", class: "btn btn-primary btn-modal", style: "margin-bottom: 10px;" %>
        </div>
      </div>
    </div>

<% end %>

app/views/dashboard/boxes/index.html.erb
<% breadcrumb :boxes %>

<div class="container">
  <section class="boxes">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <h1>Boxes</h1>
        <p>
          List of boxes visible to you.          
        </p>
        <%= render "dashboard/shared/flash" %>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th>#</th>
              <th>Box Name</th>
              <th># Items in box</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @boxes.each_with_index do |box, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= link_to  box.label, dashboard_box_items_path(box) %></td>
                <td><%= box.items.count %></td>
                  <td>
                    <%= link_to '<i class="material-icons md-18 md-dark">edit</i>'.html_safe,
                                 edit_dashboard_box_path(box),
                                 data: {toggle: 'modal', target: '#edit-box'}, remote: true %>
                    <%= link_to '<i class="material-icons md-18 md-dark">share</i>'.html_safe,
                                dashboard_box_accesses_path(box) %>
                  </td>
              <tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </section>
</div>

<!-- fab btn -->
<div class="abs-fab">
  <a href="<%= new_dashboard_box_path %>" class="btn btn-info btn-fab">
    <i class="material-icons">add</i>
  </a>
</div>
<!-- .fab btn -->

<!-- dialogs -->
<%= bootstrap_dialog_loading "edit-box" %>
<!-- .dialogs -->

app/views/dashboard/boxes/new.html.erb
<% breadcrumb :new_box %>

<div class="container">
  <section class="boxes">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <h1>Create a new box</h1>
        <p>
          Box is a top level container where items are stored.
        </p>
        <%= render "dashboard/shared/flash" %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <%= form_for @box, url: {action: "create"}, turboboost: true do |f| %>
        <div class="form-group label-static">
          <label class="control-label">Label</label>
          <%= f.text_field :label, class: "form-control" %>
        </div>
        <div>
          <%= f.submit "Create", class: "btn btn-raised btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/dashboard/boxes/update.js.erb
Turbolinks.visit('<%= @redirect_path %>');

app/views/dashboard/dashboard/home.html.erb
<% breadcrumb :root %>

<div class="container">
  <section class="boxes">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <h1>Eat me!</h1>
        <p>
          List of items that are about to expire from boxes.<br> Consume these items first.
        </p>
        <%= render "dashboard/shared/flash" %>
        <hr>
        <% @boxes.each do |box| %>
            <h3 class="btn-group-sm">
              <a href="<%= dashboard_box_items_path(box) %>"><%= box.label %></a>
              <a href="<%= new_dashboard_box_item_path(box) %>" class="btn btn-default btn-fab">
                <i class="material-icons">add</i>
              </a>
            </h3>
            <table class="table table-striped table-hover ">
              <thead>
              <tr>
                <th>#</th>
                <th>Item Name</th>
                <th>Expire in</th>
                <th>Amounts</th>
              </tr>
              </thead>
              <tbody>
              <% box.expire_in_5_days.each_with_index do |item, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td>
                      <%= link_to item.label, edit_dashboard_box_item_path(box, item, mode: 'compact'), remote: true,
                                  'data-toggle' => 'modal', 'data-target' => '#update-item'  %>
                    </td>
                    <td><%= item.expire_in %></td>
                    <td><%= item.amount %></td>
                  <tr>
              <% end %>
              </tbody>
            </table>
        <% end %>
      </div>
    </div>
  </section>
</div>

<%= bootstrap_dialog_loading "update-item" %>

app/views/dashboard/items/edit.js.erb
<% if @mode == 'compact'%>
  $('.modal').html('<%= escape_javascript(render 'dashboard/items/forms/modal_edit') %>');
<% elsif @mode == 'full' %>
  $('.modal').html('<%= escape_javascript(render 'dashboard/items/forms/modal_edit_full') %>');
<% end %>

$('.btn-modal').on('click', function() {
  $(this).attr('disabled', 'disabled');
  $(this).parents('form').submit()
});

// Register listener for date data
$('.exp').on('change', function() {
  var expireDateComps = $('.exp');
  var day = $(expireDateComps[2]).val();
  var month = $(expireDateComps[1]).val();
  var year = $(expireDateComps[0]).val();
  $('#exp-date').val(year + "-" + month + "-" + day);
});

// handle click
$('.btn-number').click(function(e){
  e.preventDefault();
  $('.btn-number').removeAttr('disabled');

  fieldName = $(this).attr('data-field');
  type      = $(this).attr('data-type');
  var input = $("input[name='"+fieldName+"']");
  var currentVal = parseInt(input.val());

  if (!isNaN(currentVal)) {
    if(type == 'minus') {
      if(currentVal > input.attr('min')) {
        input.val(currentVal - 1);
      }
      if(parseInt(input.val()) == input.attr('min')) {
        $(this).attr('disabled', true);
      }
    } else if(type == 'plus') {
      if(currentVal < input.attr('max')) {
        input.val(currentVal + 1);
      }
      if(parseInt(input.val()) == input.attr('max')) {
        $(this).attr('disabled', true);
      }
    }
  } else {
    input.val(0);
  }
});

app/views/dashboard/items/forms/_modal_edit.html.erb
<%= form_for @item,
             url: dashboard_box_item_path(@box, @item, dest: dashboard_path(@box)),
             method: :patch, remote: true do |f| %>

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4 class="modal-title"><%= @item.label %></h4>
    </div>
      <div class="modal-body">
        <div class="form-group label-static">
          <label class="control-label">Amount of item</label>
          <div class="input-group">
          <span class="input-group-btn">
          <button type="button" class="btn btn-default btn-number" data-type="minus" data-field="item[amount]">
            <span class="glyphicon glyphicon-minus"></span>
          </button>
          </span>
            <%= f.text_field :amount, class: "form-control input-number", value: "#{@item.amount}", min: "1", max: "99" %>
            <span class="input-group-btn">
          <button type="button" class="btn btn-default btn-number" data-type="plus" data-field="item[amount]">
            <span class="glyphicon glyphicon-plus"></span>
          </button>
          </span>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "Delete", dashboard_box_item_path(@box, @item, dest: dashboard_path),
                method: :delete, remote: true, class: "btn btn-raised btn-danger btn-modal" %>
        <%= f.submit "Save", class: "btn btn-primary btn-modal", style: "margin-bottom: 10px;" %>
      </div>
    </div>
  </div>

<% end %>

app/views/dashboard/items/forms/_modal_edit_full.html.erb
<%= form_for @item,
             url: dashboard_box_item_path(@box, @item, dest: dashboard_box_items_path(@box)),
             method: :patch, remote: true do |f| %>

    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title"><%= @item.label %></h4>
        </div>
        <div class="modal-body">
          <div class="form-group label-static">
            <label class="control-label">Item Name</label>
            <%= f.text_field :label, class: "form-control", autocomplete: "off" %>
          </div>
          <div class="label-static">
            <input id="exp-date" name=item[expire_date] type="hidden" value="<%= @item.expire_date %>">
            <label class="control-label">Expiration Date</label>
            <div class="row">
              <div class="col-xs-12">
                <div class="col-xs-3">
                  <div class="row">
                    <div class="form-group label-static">
                      <label class="control-label">Year</label>
                      <input class="exp form-control" data="year" type="number" placeholder="yyyy"
                              value="<%= @item.expire_date.strftime('%Y') %>" min="<%= @this_year %>">
                    </div>
                  </div>
                </div>
                <div class="col-xs-3 col-xs-offset-1">
                  <div class="row">
                    <div class="form-group label-static">
                      <label class="control-label">Month</label>
                      <input class="exp form-control" data="month" type="number" placeholder="mm"
                              value="<%= @item.expire_date.strftime('%m') %>"min="1" max="12">
                    </div>
                  </div>
                </div>
                <div class="col-xs-3 col-xs-offset-1">
                  <div class="row">
                    <div class="form-group label-static">
                      <label class="control-label">Day</label>
                      <input class="exp form-control" data="day" type="number" placeholder="dd"
                              value="<%= @item.expire_date.strftime('%d') %>" min="1" max="<%= @max_day%>">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-group label-static">
            <label class="control-label">Amount of item</label>
            <div class="input-group">
          <span class="input-group-btn">
          <button type="button" class="btn btn-default btn-number" data-type="minus" data-field="item[amount]">
            <span class="glyphicon glyphicon-minus"></span>
          </button>
          </span>
              <%= f.number_field :amount, class: "form-control input-number", value: "#{@item.amount}", min: "1", max: "99", autocomplete: 'off' %>
              <span class="input-group-btn">
          <button type="button" class="btn btn-default btn-number" data-type="plus" data-field="item[amount]">
            <span class="glyphicon glyphicon-plus"></span>
          </button>
          </span>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= link_to "Delete", dashboard_box_item_path(@box, @item, dest: dashboard_box_items_path(@box)),
                  method: :delete, remote: true, class: "btn btn-raised btn-danger btn-modal" %>
          <%= f.submit "Save", class: "btn btn-primary btn-modal", style: "margin-bottom: 10px;" %>
        </div>
      </div>
    </div>

<% end %>

app/views/dashboard/items/index.html.erb
<% breadcrumb :items, @box %>

<div class="container">
  <section class="boxes">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <h1><%= @box.label %></h1>
        <p>
          List of items belong to this box.
        </p>
        <%= render "dashboard/shared/flash" %>

        <!-- <% @items.each_with_index do |item, index| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <b><%= item.label %> </b>
              <%= link_to '<i class="material-icons md-18 md-dark">edit</i>'.html_safe,
                          edit_dashboard_box_item_path(@box, item, mode: 'full'),
                          data: {toggle: 'modal', target: '#edit-item'}, remote: true %>
            </div>
            <div class="panel-body">
              Expire Date : <%= item.expire_date %><br>
              Amount : <%= item.amount %><br>
            </div>
          </div>
        <% end %> -->

        <table class="table table-striped table-hover ">
          <thead>
          <tr>
            <th>#</th>
            <th>Item Name<br>Name (amount)</th>
            <th>Expire Date<br>yyyy-mm-dd</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @items.each_with_index do |item, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= item.label %> (<%= item.amount %>)</td>
                <td><%= item.expire_date %></td>
                <td>
                  <%= link_to '<i class="material-icons md-18 md-dark">edit</i>'.html_safe,
                              edit_dashboard_box_item_path(@box, item, mode: 'full'),
                              data: {toggle: 'modal', target: '#edit-item'}, remote: true %>
                </td>
              <tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>
</div>

<!-- fab btn -->
<div class="abs-fab">
  <a href="<%= new_dashboard_box_item_path(@box) %>" class="btn btn-info btn-fab">
    <i class="material-icons">add</i>
  </a>
</div>
<!-- .fab btn -->

<!-- dialogs -->
<%= bootstrap_dialog_loading "edit-item" %>
<!-- .dialogs -->

app/views/dashboard/items/new.html.erb
<% breadcrumb :new_item, @box %>

<div class="container">
  <section class="boxes">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <h1>Add an Item</h1>
        <p>
          Add new item into <b><%= @box.label %></b>.
        </p>
        <%= render "dashboard/shared/flash" %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
        <%= form_for @item, url: {action: "create"}, turboboost: true do |f| %>
            <div class="form-group label-static">
              <label class="control-label">Label</label>
              <%= f.text_field :label, class: "form-control", autocomplete: "off", autofocus: "true" %>
            </div>
            <div class="label-static">
              <input id="exp-date" name=item[expire_date] type="hidden">
              <label class="control-label">Expiration Date</label>
              <div class="row">
                <div class="col-xs-12">
                  <div class="col-xs-3">
                    <div class="row">
                      <div class="form-group label-static">
                        <label class="control-label">Year</label>
                        <input class="exp form-control" data="year" type="number" placeholder="yyyy"
                                min="<%= @this_year %>">
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-3 col-xs-offset-1">
                    <div class="row">
                      <div class="form-group label-static">
                        <label class="control-label">Month</label>
                        <input class="exp form-control" data="month" type="number" placeholder="mm"
                                min="1" max="12">
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-3 col-xs-offset-1">
                    <div class="row">
                      <div class="form-group label-static">
                        <label class="control-label">Day</label>
                        <input class="exp form-control" data="day" type="number" placeholder="dd"
                                min="1" max="<%= @max_day%>">
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>            
            <div class="form-group label-static">
              <label class="control-label">Item Amount</label>
              <%= f.number_field :amount, class: "form-control", autocomplete: "off" %>
            </div>
            <div>
              <%= f.submit "Add", class: "btn btn-raised btn-primary" %>
            </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

<script>
  var day, month, year;
  $('.exp').on('change', function() {
    var portion = $(this).attr('data');
    switch(portion) {
      case 'day': day = $(this).val(); break;
      case 'month': month = $(this).val(); break;
      case 'year': year = $(this).val(); break;
    }
    $('#exp-date').val(year + "-" + month + "-" + day);
  });
</script>

app/views/dashboard/shared/_loading_dialog.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    </div>
    <div class="modal-body">
      <div class="loading">
        <%= image_tag "loading.gif" %>
        <h5>Loading</h5>
      </div>
    </div>
  </div>
</div>